version: 3

images:
  base_image:
    #name: quay.io/ansible/awx-ee:latest
    name: quay.io/centos/centos:stream9  # vanilla image


dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
 